/**
 * GENERATED by scripts/generate-web-anchors.mjs — do not edit by hand.
 *
 * One entry per anchored batch: the transaction that put the root on chain, the
 * root itself, and the records it covers. The web test recomputes every root
 * from the records, so a ledger that drifted from its batches fails loudly.
 */
export interface AnchorLedgerEntry {
  chainId: number;
  chainName: string;
  explorer: string;
  tx: `0x${string}`;
  root: `0x${string}`;
  count: number;
  anchoredAt: number;
  block: number;
  recordsPath: string;
  records: Array<Record<string, unknown>>;
}

export const ANCHOR_LEDGER: AnchorLedgerEntry[] = [
  {
    "chainId": 4663,
    "chainName": "robinhood",
    "explorer": "https://robinhoodchain.blockscout.com",
    "tx": "0xad4c4d9749329274a62f7b4a2744ab66c4cec62822c7e6f6ad3630ebd00429eb",
    "root": "0x6ffe99c0512eb5033c6ad03e96fa696766bf930ea4389260c13302266d4df17b",
    "count": 2,
    "anchoredAt": 1790661167,
    "block": 75420865,
    "recordsPath": "deployments/receipts-genesis.json",
    "records": [
      {
        "kind": "name-claim",
        "chainId": 4663,
        "name": "xiaoming.musename.eth",
        "owner": "0x603b8B1f7a0Bc152b7D0Dcd7bFfBF1f2Af115f6d",
        "tx": "0x98b8fc906d1e106d0e95d1798c3196ac9875c43bfb26c8785111e663c6f47812",
        "block": 75366746,
        "at": 1790655719
      },
      {
        "kind": "card-publish",
        "chainId": 4663,
        "name": "xiaoming.musename.eth",
        "cardContentHash": "0x7eebf7476fcddf4e901df56f740488a74cf364e762d213db493c53a7321ae227",
        "tx": "0xc275bdea307b47667e527cdb3d81c92415b963d5da09922873d64140a1f8b205",
        "block": 75396854,
        "at": 1790658748
      }
    ]
  }
];
